import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import record from "../data/paintings.json"
import { useState, useEffect } from 'react'
import Link from 'next/link'
import Lottie from "react-lottie";
import animationData from '../public/lottie.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [france, setFrance] = useState(false);
  const [remy, setRemy] = useState(false);
  const [arles, setArles] = useState(false);

  const [isVisible, setIsVisible] = useState(true);

  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
  };

  useEffect(() => {
    setTimeout(() => {
      setIsVisible(false);
    }, 3000);
  }, []);


  console.log(record)

  return (
    <>
      <Head>
        <title>Art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
      <main className={styles.main}>
      <div>

    </div>
      <div className={styles.containerText}>
    
        <h1 className={styles.h1}>Choose Collection</h1>
        <div className={styles.flexBox} id="flexBox">
          <div className={styles.textWrap} id="textWrap" onClick={()=>{setFrance(true), setArles(false), setRemy(false)}}>Paris</div>
          <div className={styles.textWrap} onClick={()=>{setRemy(true), setFrance(false), setArles(false)}}>Saint Remy</div>
          <div className={styles.textWrap} onClick={()=>{setArles(true), setRemy(false), setFrance(false)}}>Arles</div>
        </div>
      </div>
      <div className={styles.wrapper}>
      {isVisible && <Lottie options={defaultOptions} height={200} width={200} />}
      {france==true &&
            record.map((rec, index) =>{
              return(
                <>{rec.class_name == "Paris" ?
                <div key={index}>
                <img className={styles.image} src={rec.image_path} width="350"></img>
                <div className={styles.title} id={index === 0 ? "titleOne" : ""} style={{width:"350px"}}>{rec.image_path.split("/").pop().split(".")[0]}</div>
                </div>: <></>}</>
              )
            })
        }
        {remy==true &&
            record.map((rec, index) =>{
              return(
                
                <>{rec.class_name == "Saint Remy" ?
                <div key={index}>
                <img className={styles.image} src={rec.image_path} width="350"></img>
                <div className={styles.title} id="title" style={{width:"350px"}}>{rec.image_path.split("/").pop().split(".")[0]}</div>
                </div>: <></>}</>
              )
            })
        }
        {arles==true &&
            record.map((rec, index) =>{
              return(
                
                <>{rec.class_name == "Arles" ?
                <div key={index}>
                <img className={styles.image} src={rec.image_path} width="350"></img>
                <div className={styles.title} id="title" style={{width:"350px"}}>{rec.image_path.split("/").pop().split(".")[0]}</div>
                </div>: <></>}</>
              )
            })
        }
        </div>
      </main>
    </>
  )
}
